### PR TITLE
DOCKER-393 Change property regex to account for spaces after comment identifier

### PR DESCRIPTION
**Pull request by Ranecdev**
See [issue](https://github.com/xenit-eu/docker-solr/issues/58)

### CODE REVIEW

**Comment by Ranecdev** [comment]
Is this something we should provide a default for? So we don't need to set it on each Shard instance

**Comment by wimfabri** [comment]
> Is this something we should provide a default for? So we don't need to set it on each Shard instance

?

**Review by wimfabri — APPROVED** [review]

**Comment by vierbergenlars** [comment]
> Is this something we should provide a default for?

Can we put the default so the backups are written in the same place as they were before by default in Alfresco?

**Comment by Ranecdev** [comment]
> Can we put the default so the backups are written in the same place as they were before by default in Alfresco?

Will do in a seperate PR

**Pull request merged**
