### PR TITLE
DOCKER-342 make repo cert alias configurable for 91-healthcheck.sh in…

### PR DESCRIPTION
**Pull request by RVanhuysseXenit**
This change would make the script compatible with the official alfresco-ss-generator project naming conventions -and other custom changes.

### CODE REVIEW

**Review by anghelutar — COMMENTED** [review]
Didn't you say you were going to implement a Java-based init script similar to Alfresco's?

**Comment by RVanhuysseXenit** [comment]
> Didn't you say you were going to implement a Java-based init script similar to Alfresco's?

Oh that's not how I understood it, sorry. I just meant that this was an issue and planned on fixing it.
If you think its the right thing to do, I start working on it?

**Comment by anghelutar** [comment]
It's me who misunderstood

**Comment by anghelutar** [comment]
If it builds, it's ok for me to merge.

**Comment by anghelutar** [comment]
Mistakenly renamed master branch and this got closed automatically.

**Pull request merged**
